export const SET_WORLD_STATS = 'SET_WORLD_STATS';
export const SELECT_COUNTRY_STATS = 'SELECT_COUNTRY_STATS';
export const REMOVE_SELECTED_COUNTRY = 'REMOVE_SELECTED_COUNTRY';
export const FILTER_CONTINENT = 'FILTER_CONTINENT';
